### ISSUE TITLE
syntax error with Python 2.7.x, not Python 3.6.x

### ISSUE THREAD

**Issue by mlaloux** [davenquinn/Attitude#1]
Hello,
Using the last version with Python 2.7.14, the command 

`` return (*self.strike_dip(), self.rake())  ``  

in  "/Library/Python/2.7/site-packages/Attitude-0.1.2-py2.7.egg/attitude/orientation/pca.py", line 399

 produces a normal  error, no problem with Python 3.6.4

**Comment by davenquinn** [comment]
Yeah this makes sense given that I haven't used it in python 2 in a while.

**Comment by davenquinn** [comment]
OK I just pushed a commit that should fix it, but it made me annoyed at python 2. I think more of these bugs will crop up in the future for sure, because some of the little stylistic things are easy to ignore. I guess we probably need python 2 support if we want this to run on ArcPy's python, yeah? What a shame...

Thanks for the input!

**Comment by mlaloux** [comment]
I don't use ArcPy (Mac OS X and Linux with Python 2.7.x and 3.6.x) but you must specify that the current version is for version 3.x and not 2.7.x because there many other  compatibility problems

**Comment by davenquinn** [comment]
Sounds good; I'd be happy to have more bugs filed to fix python 2.7 errors if you find them.
